services:
  flyway:
    image: flyway/flyway
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ${PWD}/db:/flyway/sql
      - ${PWD}/flyway.config:/flyway/conf/flyway.config
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=dct_db
    volumes:
      - db:/var/lib/postgresql/data
  api:
    profiles: ["dev"]
    build:
      context: ./server
      dockerfile: Dockerfile.local
    volumes:
      - ./server:/app
    ports:
      - "3001:3001"
    depends_on:
      - flyway
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/dct_db?schema=public"
volumes:
  db: