services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db/dct_db -schemas=public -user=postgres
      -password=password -connectRetries=5 migrate
    volumes:
      - ./db:/flyway/sql
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=dct_db
    volumes:
      - db:/var/lib/postgresql/data
  api:
    profiles: ["dev"]
    build:
      context: ./server
      dockerfile: Dockerfile.local
    volumes:
      - ./server:/app
    ports:
      - "3001:3001"
    depends_on:
      - flyway
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/dct_db?schema=public"
volumes:
  db: