services:
  flyway:
    image: flyway/flyway:9.0.1-alpine
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ${PWD}/db/migrations:/flyway/sql
      - ${PWD}/flyway.config:/flyway/conf/flyway.config
    depends_on:
      - postgres
  postgres:
    image: postgres:14.4-alpine
    restart: always
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=jstrange
    - POSTGRES_PASSWORD=pass123
    - POSTGRES_DB=dct_db