name: Execute API Integration Tests

on:
  pull_request:
    paths:
      - 'server/**'

defaults:
  run:
    working-directory: ./server

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm i
      - name: Test
        run: npm run test:integration